name: SpamTrap
author: digitalprime
authorEmail: digitalprime@sourcebin.org
authorUrl: https://github.com/digitalprime/SpamTrap
main: org.sourcebin.digitalprime.spamtrap.SpamTrapPlugin
version: 0.2.4
database: false

commands:
    spamtrapreload:
        description: reloads the spamtrap configuration file.
        aliases: [str, streload]

permissions:
    spamtrap.reload:
        default: op
    spamtrap.exempt:
        default: op
